name: ci

on:
  push:
    branches: "docker/pipeline"
  pull_request:
    branches: [ "docker/pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
  - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest

